# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: aa7c862affb7cc4fb1df69f224ab9172d01b9857bdc412711ee6a73aabf5a8a65769fab71a18bf887065b4b92f5d58eda3b29fa479facb90e42e134a6edb8683

test:
  secret_key_base: 85979e730494afb85e7c8e677f60350f08f4f21880b1fc97e28e990b3d4389b6e262aeda787c4ceaa2ec3c8fe9e160176bde7cefc8d3fd6d2eceda4fb375c3c4

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
